EVEREST-270 Return 500 instead of 502 if k8s cluster is unavailable
percona/percona-everest-backend pull request #100
Opened 2023-08-10 13:35 UTC by gen1us2k

2023-08-10 13:41 UTC, oksana-grishchenko approved these changes

2023-08-14 06:40 UTC, michal-kralik requested changes

2023-08-14 06:40 UTC, michal-kralik commented on public/dist/index.html
> +  <!DOCTYPE html>
Why do we need this file?

2023-08-14 06:40 UTC, michal-kralik commented on api/proxy.go
> +	req.Header.Set(everestKubernetesHeader, cluster.Name)
Why do we set the header?

2023-08-14 06:40 UTC, michal-kralik commented on api/proxy.go
> +		b, _ := json.Marshal(Error{Message: pointer.ToString(errorMessage)}) //nolint:errchkjson
Let's check the error please

2023-08-14 06:40 UTC, michal-kralik commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadRequest)
We shall use a different status code. This is not a bad a request since we could not connect to k8s cluster.

2023-08-14 06:40 UTC, michal-kralik commented on api/proxy.go
> +	if errors.Is(err, syscall.ECONNREFUSED) {
Let's please include other reasons for errors, such as timeouts, etc.

2023-08-14 06:40 UTC, michal-kralik commented on api/proxy.go
> +		res.Write(b)                                                         //nolint:errcheck,gosec
Let's please check the error

2023-08-14 06:40 UTC, michal-kralik commented on api/proxy.go
> +	return fmt.Sprintf("/apis/everest.percona.com/v1alpha1/namespaces/%s%s%s", namespace, uri, resourceName)
We don't properly sanitize the url components. This opens us to url attacks. Let's please sanitize the values.

2023-08-14 06:40 UTC, michal-kralik commented on api/proxy.go
> +	res.WriteHeader(http.StatusBadGateway)
Since we're handling errors, let's please return a meaningful default error.

2023-08-14 07:05 UTC, gen1us2k commented on api/proxy.go
> +	req.Header.Set(everestKubernetesHeader, cluster.Name)
So we can get the name from the header for a kubernetes cluster.

2023-08-14 07:22 UTC, michal-kralik commented on api/proxy.go
> +	req.Header.Set(everestKubernetesHeader, cluster.Name)
there's no benefit in storing it in the header

2023-08-14 07:40 UTC, gen1us2k commented on api/proxy.go
> +	req.Header.Set(everestKubernetesHeader, cluster.Name)
What alternatives do you see?

2023-08-14 07:41 UTC, gen1us2k commented on api/proxy.go
> +	return fmt.Sprintf("/apis/everest.percona.com/v1alpha1/namespaces/%s%s%s", namespace, uri, resourceName)
namespace comes from the db and we do sanitization before storing it. As for other params we have this covered by oapi

2023-08-14 07:59 UTC, michal-kralik commented on api/proxy.go
> +	return fmt.Sprintf("/apis/everest.percona.com/v1alpha1/namespaces/%s%s%s", namespace, uri, resourceName)
Can you please point me to the part of code which sanitizes `resourceName`? I could not find it.

2023-08-14 08:01 UTC, michal-kralik commented on api/proxy.go
> +	req.Header.Set(everestKubernetesHeader, cluster.Name)
In case we need the cluster name for any purposes, we shall pass it to the function which requires it instead of modifying the headers. In this case it would be `errorHandler`.

2023-08-14 08:11 UTC, michal-kralik requested changes

2023-08-14 08:11 UTC, michal-kralik commented on api/proxy.go
> +	defer logger.Sync()
We already have the logger initialized, why do we need to initialize it again?

2023-08-14 08:11 UTC, michal-kralik commented on api/proxy.go
> +	if errors.Is(err, syscall.ECONNREFUSED) || errors.Is(err, os.ErrDeadlineExceeded) {
This will never be true, because you're checking an error from `json.Marshal`.

2023-08-14 08:31 UTC, gen1us2k commented on api/proxy.go
> +	defer logger.Sync()
because net/http.Proxy does not know anything about it

2023-08-14 08:34 UTC, gen1us2k commented on api/proxy.go
> +	defer logger.Sync()
We can use fmt.Println instead

2023-08-14 08:38 UTC, gen1us2k commented on api/proxy.go
> +	req.Header.Set(everestKubernetesHeader, cluster.Name)
I don't want to implement a custom proxy just to store it using variable names and make it thread-safe. Storing the k8s name in headers is just the simplest solution we can have right now because proxy.ErrorHandler and other structs have their own signature we need to follow. As another solution, we can pass the name to a function that returns the handler but I'm not sure that it will work reliably keeping in mind multik8s support

2023-08-14 08:39 UTC, gen1us2k commented on api/proxy.go
> +	req.Header.Set(everestKubernetesHeader, cluster.Name)
So a benefit of using headers is that it's a thread-safe, simple solution without any wrappers around the standard and implemented stuff we use.

2023-08-14 09:32 UTC, michal-kralik requested changes

2023-08-14 09:32 UTC, michal-kralik commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
As mentioned in the original comment, let's please handle the default error in a consistent manner by returning `{message:""}` json object with a meaningful error message.

2023-08-14 09:32 UTC, michal-kralik commented on api/proxy.go
> +	return fmt.Sprintf("/apis/everest.percona.com/v1alpha1/namespaces/%s%s%s", namespace, uri, resourceName)
The middleware validates if the `name` parameter is present. It does not perform any sanitization.
As far as I know it does not check if the resource name is not for example `../name`
Happy to explain how this can be misused over Slack if needed.

2023-08-14 09:44 UTC, gen1us2k commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
It returns it

2023-08-14 09:44 UTC, gen1us2k commented on api/proxy.go
> +	return fmt.Sprintf("/apis/everest.percona.com/v1alpha1/namespaces/%s%s%s", namespace, uri, resourceName)
This is out of the scope of this PR. I'll create a new ticket for that

2023-08-14 09:45 UTC, gen1us2k commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
line 107

2023-08-14 10:56 UTC, recharte commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
@gen1us2k it seems to me that in line 107 we'll return "%s kubernetes cluster is unavailable" just like in line 101. Am I missing something?

2023-08-14 11:02 UTC, gen1us2k commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
https://github.com/percona/percona-everest-backend/blob/657580afe828def96fd3d01fa7988d974ce7abb6/api/proxy.go#L106-L109

2023-08-14 11:04 UTC, recharte commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
Yes, but what's the content of `b`? It seems to me like it will always be "%s kubernetes cluster is unavailable" regardless of returning 500 (line 101) or 502 (line 107)

2023-08-14 11:15 UTC, gen1us2k commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
Yep. Because when errorHandler is being called it means that k8s cluster is unavailable anyway

2023-08-14 11:17 UTC, recharte commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
In that case why use 500 for `syscall.ECONNREFUSED` and `os.ErrDeadlineExceeded` and 502 for everything else?

2023-08-14 11:52 UTC, gen1us2k commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
FE handles 500 only afaik and the webpage hangs and do not inform the end-user on 502 error

2023-08-14 12:21 UTC, michal-kralik commented on api/proxy.go
> +	return fmt.Sprintf("/apis/everest.percona.com/v1alpha1/namespaces/%s%s%s", namespace, uri, resourceName)
Please link it here for reference

2023-08-14 12:22 UTC, michal-kralik submitted a review, later dismissed
Let's please resolve the pending conversations about a security issue ticket and default error being handled properly.

2023-08-14 12:44 UTC, gen1us2k commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
Let's see it in the future. Right now the issue with 502

2023-08-14 12:57 UTC, gen1us2k commented on api/proxy.go
> +		res.WriteHeader(http.StatusBadGateway)
It returns 500 in every scenario. I wanted to return 502 for some other unhandled cases to keep the default behavior of HttpSingleHostProxy

2023-08-14 13:03 UTC, merged