EVEREST-204 Edit BackupStorages
percona/percona-everest-backend pull request #101
Opened 2023-08-10 16:12 UTC by oksana-grishchenko

EVEREST-204

2023-08-11 08:29 UTC, gen1us2k approved these changes

2023-08-14 06:50 UTC, michal-kralik requested changes

2023-08-14 06:50 UTC, michal-kralik commented on api/backup_storage.go
> +	tx := e.storage.Begin(c)
We're creating a tx but not using it later. The `tx.Rollback()` will have no effect.

2023-08-14 06:50 UTC, michal-kralik commented on api/backup_storage.go
> +	}
We shall reconsider this logic.
In case one of the k8s cluster updates fail, we end up in an inconsistent state, where some clusters have been updated, while others were not.

2023-08-14 07:46 UTC, oksana-grishchenko commented on api/backup_storage.go
> +	tx := e.storage.Begin(c)
@michal-kralik  what do you mean? `tx.Rollback()` is called to rollback the changes in case the k8s objects are failed to be updated, the `tx.Commit()` is called if the changes were applied successfully.

2023-08-14 07:46 UTC, oksana-grishchenko commented on api/backup_storage.go
> +	}
The multi-k8s support for BackupStorages is gonna be resolved in the scope of EVEREST-257. I agree the storages needs to be consistent across all k8s clusters for all methods we have.

2023-08-14 08:14 UTC, michal-kralik commented on api/backup_storage.go
> +	}
Since it's not part of this this ticket, can we remove this functionality? In this state, I believe it's broken and will cause issues.

2023-08-14 08:15 UTC, michal-kralik commented on api/backup_storage.go
> +	tx := e.storage.Begin(c)
That's true, however in order to execute a query within a transaction, you need to call methods on the `tx` object.
See https://gorm.io/docs/transactions.html for more details.
Happy to jump on a call to explain in more detail if needed.

2023-08-14 08:15 UTC, michal-kralik requested changes
We shall address outstanding conversations.

2023-08-14 09:27 UTC, oksana-grishchenko commented on api/backup_storage.go
> +	}
The approach however works for a single k8s cluster that we support now. So to address the concern regarding inconsistent state in case of an error for multi k8s, the method now throws an error in case there are several k8s clusters, so we can keep the value for single cluster and prevent inconsistence for multiple. Wdyt?

2023-08-14 09:37 UTC, michal-kralik commented on api/backup_storage.go
> +	}
I think it's more consistent with the single k8s cluster approach we have.

2023-08-14 09:37 UTC, michal-kralik approved these changes
Looks great, thank you

2023-08-14 10:14 UTC, merged