EVEREST-248 Make kubernetes error messages userfriendly
percona/percona-everest-backend pull request #102
Opened 2023-08-11 08:19 UTC by gen1us2k

https://jira.percona.com/browse/EVEREST-248

PR based on the changes in https://github.com/percona/percona-everest-backend/pull/100

2023-08-14 06:42 UTC, michal-kralik requested changes
Let's please address comments in #100 first

2023-08-14 15:18 UTC, recharte commented on api/proxy.go
> +func everestModifier(resp *http.Response) error {
I think we should rename this function to something more meaningful, it should allude to the modification it does which is this case is to change the status message if we face an error.
Something like
```suggestion
func mapStatusMessageCRDsOnError(resp *http.Response) error {
```

2023-08-14 21:02 UTC, oksana-grishchenko approved these changes
Looks great! 
I thought it would be great to have unit-tests for the error messaging, which will also serve as a documentation about how it works, but it might change the scope, so leaving it up to you.

2023-08-15 06:15 UTC, michal-kralik approved these changes

2023-08-15 08:45 UTC, merged