EVEREST-269 Renamed ObjectStorage to BackupStorage
percona/percona-everest-backend pull request #111
Opened 2023-08-15 10:05 UTC by gen1us2k

2023-08-15 12:17 UTC, michal-kralik commented
I'd like to do this in my PR for monitoring if possible.
Otherwise there will be tons of conflicts and I'll have hard time merging this.

2023-08-16 07:57 UTC, oksana-grishchenko commented on api/database_cluster.go
> +	err := e.deleteBackupStorages(ctx.Request().Context(), kubernetesID, name)
I'm concerned about the naming, which becomes confusing when there are both k8s resource and Everest object have exactly the same name. 
For example here - when a DBCluster is deleted, we try to delete the related storage CRs from k8s. We don't touch the Everest object here, however from this naming I would assume we delete everything. So to understand what's happening we need to dive into details each time.

what about having a prefix like `k8s`? So we'll have `backupStorages` for Everest objects and `k8sBackupStorages` for k8s objects.

2023-08-16 08:04 UTC, gen1us2k commented on api/database_cluster.go
> +	err := e.deleteBackupStorages(ctx.Request().Context(), kubernetesID, name)
I use use k8s prefix for k8s related objects

2023-08-16 08:21 UTC, oksana-grishchenko commented on api/database_cluster.go
> +	err := e.deleteBackupStorages(ctx.Request().Context(), kubernetesID, name)
I see, I can find the `updateK8SBackupStorages` method, which is what I would like to have. But why we don't have the prefix in the `deleteBackupStorages` and `createBackupStorages` methods? That methods also operates with k8s objects only.

2023-08-16 09:08 UTC, gen1us2k commented
@michal-kralik Unfortunately no because the issue is on me and I made everything ready to merge.

2023-08-16 09:08 UTC, oksana-grishchenko approved these changes

2023-08-16 09:16 UTC, michal-kralik commented
> @michal-kralik Unfortunately no because the issue is on me and I made everything ready to merge.

I can make the changes in my PR.
It's going to be tons of work if we merge this first instead of me making the changes in the other PR which will further postpone the delivery.

2023-08-16 10:31 UTC, recharte commented
> 

@michal-kralik As discussed offline, this issue is blocking the FE development for the backups and that's a higher priority now compared to the monitoring part. Let's not block this due to the monitoring PR.
Sorry for the extra work you'll have to do fixing the conflicts.

2023-08-16 11:37 UTC, recharte requested changes

2023-08-16 11:37 UTC, recharte commented on pkg/kubernetes/client/object_storage.go
You should also rename this file.

2023-08-16 11:37 UTC, recharte commented on public/dist/index.html
> +
Why is this part of this PR? Was it intentional?

2023-08-16 11:40 UTC, gen1us2k commented on public/dist/index.html
> +
Nah. I just test be with fe locally and it makes these changes

2023-08-16 15:17 UTC, merged