Readme updates installations steps
percona/percona-everest-backend pull request #114
Opened 2023-08-18 12:17 UTC by rasika-chivate

Update the readme.

2023-08-18 12:17 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-everest-backend?pullRequest=114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-everest-backend?pullRequest=114) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-everest-backend?pullRequest=114) it.</sub>

2023-08-18 12:28 UTC, recharte submitted a review, later dismissed

2023-08-18 12:28 UTC, oksana-grishchenko approved these changes

2023-08-18 12:28 UTC, oksana-grishchenko commented on README.md
> +  ```
A bit confusing that the downloaded file looks like `everestctl-darwin-amd64`, and the name is used in the step 5, but here the rights are applied to the `everestctl`

2023-08-18 14:59 UTC, hors requested changes
@rasika-chivate please add the task number to this PR

https://jira.percona.com/browse/EVEREST-293

2023-08-18 15:08 UTC, hors requested changes

2023-08-18 15:08 UTC, hors commented on README.md
> +  ```
We need to use `everestctl-darwin-amd64` in all places or rename it and use `everestctl` then.

2023-08-18 15:08 UTC, hors commented on README.md
> +4. Get a kubeconfig file and rename it to `config.yaml`.
I prefer to skip this point because sometimes it is not enough just to get `kubeconfig`. E.g. in the case of EKS you need to have additional dependencies and access to AWS itself. The same for GKE. We have `## Creating Kubernetes cluster` it should be enough to understand that you need to have access to it.

2023-08-21 09:21 UTC, rasika-chivate commented on README.md
> +4. Get a kubeconfig file and rename it to `config.yaml`.
ok

2023-08-21 10:22 UTC, hors requested changes

2023-08-21 10:22 UTC, hors commented on README.md
> +  ```
@rasika-chivate I suggest to use `everestctl-darwin-amd64 `in all places or add the command how to rename it to `everestctl` and then use `everestctl`

2023-08-21 10:23 UTC, hors commented on README.md
> +   ./everestctl-darwin-amd64 install operators --backup.enable=false --everest.endpoint=http://127.0.0.1:8080 --monitoring.enable=false --operator.mongodb=true --operator.postgresql=true --operator.x
```suggestion
   ./everestctl-darwin-amd64 install operators --backup.enable=false --everest.endpoint=http://127.0.0.1:8080 --monitoring.enable=false --operator.mongodb=true --operator.postgresql=true --operator.xtradb-cluster=true --skip-wizard
```

2023-08-21 11:42 UTC, recharte commented on README.md
> +  ```
@rasika-chivate Please just add an extra step to rename the file like `mv everestctl-darwin-amd64 everestctl` and state that `everestctl-darwin-amd64` is a place holder and that the user should change it according to the file downloaded in the previous step.

2023-08-21 13:04 UTC, recharte approved these changes

2023-08-21 13:08 UTC, oksana-grishchenko approved these changes

2023-08-22 08:00 UTC, merged

2023-08-22 09:48 UTC, PeterSzcz commented on README.md
> +2. Rename the downloaded file as follows:
we don't need to rename if we changed name in script below right? the whole idea was to skip mv step and just keep the chmod, or am I wrong?

2023-08-22 09:51 UTC, PeterSzcz commented on README.md
> +4. Get a kubeconfig file and rename it to `config.yaml`.
In my email I've added a part about default k8s config location, we should add this here "(this step is optional if you have your kubeconfig file in ./kube/config/ you can skip this step)"

2023-08-22 09:51 UTC, PeterSzcz commented on README.md
>  ✗ ./everestctl install operators
this shoudl also be everest-darwin-adm64