EVEREST-317 contributing guidelines
percona/percona-everest-backend pull request #134
Opened 2023-08-30 10:12 UTC by gen1us2k

EVEREST-317

Guidelines for every team member in the BE team to follow

Limitations and boundaries we have for Everest
Handling k8s versions and using k8s features
Working with Git
Go best practices and code style
Operator best practices and code style
Principles we follow
How to make a proposal to change something
PR requirements
How to prepare PR
How to review PR

2023-08-30 16:39 UTC, oksana-grishchenko commented on docs/process/GIT_AND_GITHUB.md
> +    Should the person assigned as a reviewer not be able to review the PR in due time, they must un-assign themselves as a a reviewer of the said PR.
I think this is never gonna happen. Usually a reviewer doesn't review for the following reasons:
- out of office
- missed notification
- too busy 

none of the cases will ever lead to "un-assign themselves". 

another question - what is the "due time"?

2023-08-30 16:39 UTC, oksana-grishchenko commented on docs/process/GIT_AND_GITHUB.md
> +10. If you implement a new Feature or make an Improvement or Fix a Bug - add a link in the Long Description to the related PR for Feature Build.
We don't have Feature Builds, perhaps we should update this line

2023-08-30 16:39 UTC, oksana-grishchenko commented on docs/process/GIT_AND_GITHUB.md
> +3. Be polite and ask questions instead of suggesting solutions. E.g. Why did you decide to use x instead of y?
sometimes suggesting a solution is not that bad if a proper reason is provided. I mean, if one has something in mind than it's better to (politely) communicate the idea instead of asking leading questions that will increase the review time.

2023-08-30 16:39 UTC, oksana-grishchenko commented on docs/process/README.md
> +10. We do not optimize something prematurely
This list sounds great, love it! 

However we may still have hard times because of the different understanding of each point. 
One says "KISS and YAGNI" another says "Inexpensive Adaptability" and "Stable Productivity".  

There is no such thing as "self explanatory". We could build it as a team though via discussing that principles regularly.

2023-08-30 16:39 UTC, oksana-grishchenko commented on docs/process/go_best_practices.md
> +- All gRPC errors are returned as status messages ([1](https://godoc.org/google.golang.org/grpc/status), [2](https://godoc.org/google.golang.org/genproto/googleapis/rpc/status)). They contain a [code
do we need the grpc-section? what about kiss and yagni? :)

2023-08-30 16:39 UTC, oksana-grishchenko commented on docs/process/go_best_practices.md
> +- `gofumpt -s ` (note the `-s`)
do we need this? if so, should we put it under `make format`?

2023-08-30 16:39 UTC, oksana-grishchenko commented on docs/process/go_best_practices.md
> +    ```
`make format` takes care of the imports, should we still keep this section?

2023-08-30 16:39 UTC, oksana-grishchenko commented on docs/process/go_best_practices.md
> +- golangci-lint checks style too.
let's replace it with `make check` since we have the `make format` above

2023-08-31 07:22 UTC, hors commented on docs/process/GIT_AND_GITHUB.md
> +# Working with Git and GitHub
I am not sure that it is the right place for this doc. I prefer to have it in Notion or it should be a part of the contribution guide.

2023-08-31 07:22 UTC, hors commented on docs/process/GIT_AND_GITHUB.md
> +    - [x] All tests in the PR pass.
Please create PR template for it

2023-08-31 07:22 UTC, hors commented on docs/process/GIT_AND_GITHUB.md
> +7. Delete the branch after merging the PR (note: this step may be automated for some of our repos, i.e. a bot deletes the branch right after the merge).
it can be done via github configuration

2023-08-31 08:17 UTC, gen1us2k commented on docs/process/GIT_AND_GITHUB.md
> +# Working with Git and GitHub
I'll move it to notion later. However this might be helpful for external contributors

2023-08-31 08:22 UTC, gen1us2k commented on docs/process/GIT_AND_GITHUB.md
> +3. Be polite and ask questions instead of suggesting solutions. E.g. Why did you decide to use x instead of y?
Yeah. Makes sense. I'll try to add some suggestions here

2023-08-31 08:33 UTC, gen1us2k commented on .github/pull_request_template.md
> +
What should we remove or add here?

2023-08-31 09:16 UTC, gen1us2k commented on docs/process/README.md
> +10. We do not optimize something prematurely
Yeah. Thanks for pointing it and I'll try to elaborate and make it clear to everyone

2023-09-05 15:02 UTC, oksana-grishchenko commented on .github/pull_request_template.md
> +
I would suggest to add the list of the related PRs in format 
```
Related PRs:
-  [link]
```

The links list allows to navigate between PRs easier and this dash sign allows to see the status of the PR, which is really convenient. I mean, here is how it looks with a forehand dash:

-  https://github.com/percona/percona-everest-backend/pull/134

and here is how it looks without it:

https://github.com/percona/percona-everest-backend/pull/134

2023-09-05 15:02 UTC, oksana-grishchenko commented on docs/process/README.md
> +10. We do not optimize something prematurely
Thanks for providing more details!

2023-09-05 15:06 UTC, oksana-grishchenko approved these changes
Thanks Andrew for this initiative, great job!

My concerns are resolved, so hereby I accept the rules.

2023-09-06 07:43 UTC, gen1us2k commented on .github/pull_request_template.md
> +
Added. Thanks for the suggestion

2023-09-06 08:06 UTC, michal-kralik approved these changes
Good job Andrew

2023-09-07 07:49 UTC, recharte requested changes
Great job @gen1us2k I really enjoyed this :clap:
However, I added a few suggestions.

2023-09-07 07:49 UTC, recharte commented on .github/pull_request_template.md
A "How was it tested" section could be useful.
Maybe something like this. WDYT?
# How was it tested?
_Describe step-by-step **what** and **how** you have tested, always asserting the test result. If possible, show the commands you ran and their output (if relevant/applicable).
Attach or link also any helper scripts and list any relevant details for your test configuration._

### Setup:
* **Environment:** 
* **Relevant configurations:**

``````

### Steps:
1. Do X: `./x 12 34`
2. **Assert:** Y happened

```
    <Include command that checks the outcome and it's output>
```

2023-09-07 07:49 UTC, recharte commented on docs/process/GIT_AND_GITHUB.md
> +8. If you open a Pull Request to fix a Bug - put an explanation in the Long Description about the Bug. It may contain information about how it affects the component. Also, it's good to have short ref
> (now applicable only to mongodb_exporter and proxysql_exporter)

???

2023-09-07 07:49 UTC, recharte commented on docs/process/README.md
> +1. **We will not ship garbage.** All the code should be tested before we ship it!
Since this a public document maybe we should go with a softer language.
```suggestion
1. **We will not ship untested code.** All the code should be tested before we ship it!

```

2023-09-07 07:49 UTC, recharte commented on docs/process/README.md
> +    * The phrase “This system needs to be redesigned” is an admission of failure, we don’t want a new system that does exactly the same as the old one”.
Mistakes happen, wrong decisions will be made. We shouldn't object these types of improvements. Of course it would be great if we could avoid them in the first place but I definitely wouldn't critique an improvement because it admits a previous failure. Admitting that something needs to change is a proof that we can do better and that we are constantly evolving, this is a good thing, we should embrace it and not shut it down.

2023-09-07 07:49 UTC, recharte commented on docs/process/README.md
> +6. **QA will find nothing!** We will make sure the code is tested before it reaches QA, to speed up this process.
I understand the good principle behind this but I don't think that `QA will find nothing!` is a good statement, it questions our QA team. Also we already kinda state this in point 1.
> All the code should be tested before we ship it!

2023-09-07 08:14 UTC, gen1us2k commented on docs/process/README.md
> +6. **QA will find nothing!** We will make sure the code is tested before it reaches QA, to speed up this process.
Of course they will find something but we as developers need to implement bulletproof solutions and all corner cases should be handled. Basically it means that we care about the quality and do not rely on QA team to find bugs and we try find them by ourselves

2023-09-07 08:15 UTC, gen1us2k commented on docs/process/README.md
> +    * The phrase “This system needs to be redesigned” is an admission of failure, we don’t want a new system that does exactly the same as the old one”.
idk what to do here. Should I improve something?

2023-09-07 08:23 UTC, gen1us2k commented on docs/process/README.md
> +6. **QA will find nothing!** We will make sure the code is tested before it reaches QA, to speed up this process.
Added second point

2023-09-07 08:24 UTC, recharte commented on docs/process/README.md
> +    * The phrase “This system needs to be redesigned” is an admission of failure, we don’t want a new system that does exactly the same as the old one”.
I would just remove this second point. I don't agree with it at all for the aforementioned reasons.
Obviously I can't (or want to) impose anything. This is a team's document so the team should agree on everything in this document.
@michal-kralik @oksana-grishchenko what do you guys think about this?

2023-09-07 08:28 UTC, recharte commented on docs/process/README.md
> +6. **QA will find nothing!** We will make sure the code is tested before it reaches QA, to speed up this process.
Cool, what do you think of this suggestion? It's aligned with our recent POGs without questioning other teams :slightly_smiling_face: 

6. **Bugs shall not pass!** We will make sure the code is tested before it reaches QA, to speed up this process. We implement bulletproof solutions where all corner cases should be handled

2023-09-07 08:38 UTC, gen1us2k commented on docs/process/README.md
> +    * The phrase “This system needs to be redesigned” is an admission of failure, we don’t want a new system that does exactly the same as the old one”.
Nah. Because we do not build a new system that does exactly the same as the old one.  I have an example from the real-life. We didn't build Everest the same way as it was implemented in PMM. We learned from our mistakes, added some points, and designed it in a new way.  The whole point is about this and I agree that mistakes may happen. But we do not need to redesign just for the sake of redesigning stuff. Instead, we should implement a completely new design.

Also, during the time we will redesign some parts of the system but not the whole system.

2023-09-07 08:39 UTC, gen1us2k commented on docs/process/README.md
> +6. **QA will find nothing!** We will make sure the code is tested before it reaches QA, to speed up this process.
Great suggestion. Thanks. I added it.

2023-09-07 08:45 UTC, gen1us2k commented on docs/process/README.md
> +    * The phrase “This system needs to be redesigned” is an admission of failure, we don’t want a new system that does exactly the same as the old one”.
I clarified some parts

2023-09-07 09:11 UTC, recharte commented on docs/process/README.md
> +    * The phrase “This system needs to be redesigned” is an admission of failure, we don’t want a new system that does exactly the same as the old one”.
Ok, I understand that the main takeaway we want from this point is "we do not need to redesign just for the sake of redesigning stuff" and we should seek continuous improvements.
What do you think about the following suggestion? Does it convey the message without the negative connotation of failure?

`We want to nurture a culture of continuous improvement rather than undertaking full system redesigns merely for the sake of change. We shall focus on making incremental enhancements that not only deliver tangible value but also maintain the team's productivity.`

2023-09-07 09:14 UTC, gen1us2k commented on docs/process/README.md
> +    * The phrase “This system needs to be redesigned” is an admission of failure, we don’t want a new system that does exactly the same as the old one”.
Sounds great. Changed

2023-09-07 09:15 UTC, recharte approved these changes
Well done :muscle:

2023-09-07 10:35 UTC, merged