EVEREST-399 add possibility of deploying everest in k8s
percona/percona-everest-backend pull request #152
Opened 2023-09-11 13:22 UTC by hors

* for now we do not have help chart which is why it is good
      the idea to create a simple yaml file that contains one sts
      for everest itself and two services
    * move docker-compose.yml and quickstart.yml under the deploy dir

2023-09-11 13:22 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-everest-backend?pullRequest=152) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-everest-backend?pullRequest=152) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-everest-backend?pullRequest=152) it.</sub>

2023-09-11 13:28 UTC, hors commented on deploy/everest-sts-quickstart.yaml
> +apiVersion: apps/v1
What do you think about moving these files under deploy dir? If it is a good idea, should we change any pipelines?

2023-09-11 13:29 UTC, hors reviewed
What do you think about moving these files under deploy dir? If it is a good idea, should we change any pipelines?

2023-09-11 13:30 UTC, hors commented on deploy/everest-sts-quickstart.yaml
> +  name: percona-everest
we need to choose name and all labels

2023-09-11 13:32 UTC, hors commented on deploy/everest-sts-quickstart.yaml
Does it ok to have this name?

2023-09-11 13:32 UTC, hors commented on deploy/everest-sts-quickstart.yaml
> +          image: perconalab/everest:v0.2.0
Maybe we need to deploy dev-latest...

2023-09-11 13:32 UTC, hors commented on deploy/everest-sts-quickstart.yaml
> +          storage: 2Gi
By default 2G for PVC. Is it ok?

2023-09-11 13:43 UTC, gen1us2k commented
>What do you think about moving these files under deploy dir? If it is a good idea, should we change any pipelines/tests?

quickstart.yml looks like a great candidate to move to deploy dir, however, we use docker-compose.yml for local development and it's something developer related.

The pipeline will be fixed once you move docker-compose.yaml back to the project root

2023-09-11 13:57 UTC, gen1us2k commented on deploy/everest-sts-quickstart.yaml
deploy/sts-quickstart.yaml looks better imo

2023-09-11 13:57 UTC, gen1us2k commented on deploy/everest-sts-quickstart.yaml
> +  name: percona-everest
percona-everest for the stateful set looks good. We can use percona-everest prefix for everything just to keep it consistent

2023-09-11 14:14 UTC, recharte commented
> What do you think about moving these files under deploy dir? If it is a good idea, should we change any pipelines/tests?

I think yes, we should move it to the deploy dir. We actually need to bootstrap this pipeline, right now the deploy bundle isn't being automatically generated.

2023-09-11 14:16 UTC, recharte commented on deploy/everest-sts-quickstart.yaml
> +          image: perconalab/everest:v0.2.0
Yes, IMO the main branch should use dev-latest and this should be changed every time we create a new release branch/tag.

2023-09-11 14:18 UTC, recharte commented on deploy/everest-sts-quickstart.yaml
> +          storage: 2Gi
Since we need to support thousands of DB clusters we need to check how the everest internal data usage actually grows with it but I'm pretty sure 2GiB is way more than we need.

2023-09-11 14:25 UTC, hors commented on deploy/everest-sts-quickstart.yaml
> +          storage: 2Gi
@recharte I can set 1G :)

2023-09-11 14:26 UTC, recharte commented on deploy/everest-sts-quickstart.yaml
> +          storage: 2Gi
I think 1G is most definitely fine for now

2023-09-11 14:32 UTC, hors commented on deploy/everest-sts-quickstart.yaml
done https://github.com/percona/percona-everest-backend/pull/152/commits/5b857e6dc329185249b9e6f1edb2208b798879d8

2023-09-11 14:32 UTC, hors commented on deploy/everest-sts-quickstart.yaml
> +          image: perconalab/everest:v0.2.0
done https://github.com/percona/percona-everest-backend/pull/152/commits/5b857e6dc329185249b9e6f1edb2208b798879d8

2023-09-11 14:34 UTC, hors commented on deploy/everest-sts-quickstart.yaml
> +          storage: 2Gi
https://github.com/percona/percona-everest-backend/pull/152/commits/97aa52fc8cc97fa68e0101eae2439706ec705532

2023-09-11 14:41 UTC, gen1us2k approved these changes

2023-09-11 18:50 UTC, hors commented
> > > @recharte @gen1us2k we need to decide what we need to do with docker-compose.yaml :)
> > 
> > 
> > move it to the root dir =)
> 
> @gen1us2k @hors Why don't we keep both of them in the deploy dir but name them something like `quickstart-compose.yml` and `quickstart-k8s.yml`?

@gen1us2k can we change our tests to use `quickstart-compose.yml` from the deploy dir?

2023-09-12 06:29 UTC, gen1us2k commented
@hors I'll create a ticket for that

2023-09-12 06:50 UTC, hors commented
> > > @recharte @gen1us2k we need to decide what we need to do with docker-compose.yaml :)
> > 
> > 
> > move it to the root dir =)
> 
> @gen1us2k @hors Why don't we keep both of them in the deploy dir but name them something like `quickstart-compose.yml` and `quickstart-k8s.yml`?

https://github.com/percona/percona-everest-backend/pull/152/commits/a47ce0cb1f21f50de19c1816824feb73327f37f0

2023-09-12 08:14 UTC, oksana-grishchenko approved these changes
A great idea, thanks for implementing this! 

> What do you think about moving these files under deploy dir? 

it looks consistent, especially with the new naming for the files.

2023-09-12 10:20 UTC, recharte approved these changes

2023-09-12 10:23 UTC, recharte requested changes

2023-09-12 10:23 UTC, recharte commented on deploy/quickstart-k8s.yaml
> +      app.kubernetes.io/name: percona-everet-backend
```suggestion
      app.kubernetes.io/name: percona-everest-backend
```

2023-09-12 10:23 UTC, recharte commented on deploy/quickstart-k8s.yaml
> +        app.kubernetes.io/name: percona-everet-backend
```suggestion
        app.kubernetes.io/name: percona-everest-backend
```

2023-09-12 10:23 UTC, recharte commented on deploy/quickstart-k8s.yaml
> +                app.kubernetes.io/name: percona-everet-backend
```suggestion
                app.kubernetes.io/name: percona-everest-backend
```

2023-09-12 10:23 UTC, recharte commented on deploy/quickstart-k8s.yaml
> +    app.kubernetes.io/name: percona-everet-backend
```suggestion
    app.kubernetes.io/name: percona-everest-backend
```

2023-09-12 10:23 UTC, recharte commented on deploy/quickstart-k8s.yaml
> +    app.kubernetes.io/name: percona-everet-backend
```suggestion
    app.kubernetes.io/name: percona-everest-backend
```

2023-09-12 10:23 UTC, recharte commented on deploy/quickstart-k8s.yaml
> +    app.kubernetes.io/name: percona-everet-backend
```suggestion
    app.kubernetes.io/name: percona-everest-backend
```

2023-09-12 10:23 UTC, recharte commented on deploy/quickstart-k8s.yaml
> +    app.kubernetes.io/name: percona-everet-backend
```suggestion
    app.kubernetes.io/name: percona-everest-backend
```

2023-09-12 21:41 UTC, merged