EVEREST-434 move to errors package
percona/percona-everest-backend pull request #171
Opened 2023-09-20 18:41 UTC by gen1us2k

**CHANGE DESCRIPTION**
---
**Problem:**
EVEREST-434

*Short explanation of the problem.*

**Related pull requests**

- [link]

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?

**Tests**
- [ ] Is an Integration test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?

2023-09-20 21:41 UTC, oksana-grishchenko reviewed
`pkg/errors` still can be found in go.mod and tests 
<img width="956" alt="Screenshot 2023-09-20 at 23 39 53" src="https://github.com/percona/percona-everest-backend/assets/91597950/d1982e06-bb9c-47bf-a170-f94ddcce13ac">

2023-09-21 08:35 UTC, recharte approved these changes

2023-09-21 09:43 UTC, gen1us2k commented
@oksana-grishchenko migrated tests but it's present in mod files because dependencies use it

2023-09-21 09:54 UTC, oksana-grishchenko approved these changes

2023-09-21 10:04 UTC, merged

2023-09-21 10:06 UTC, michal-kralik requested changes

2023-09-21 10:06 UTC, michal-kralik commented on pkg/kubernetes/configs.go
> +		return errors.Join(err, errors.New("could not update config in Kubernetes"))
We need to update this line. It will always return an error whereas before it returned `nil`.

2023-09-21 13:32 UTC, michal-kralik commented on pkg/kubernetes/configs.go
> +		return errors.Join(err, errors.New("could not update config in Kubernetes"))
`err` can be `nil` as returned on line 228.
Before it returned either `nil` or a wrapped `err` depending on the value of `err`