EVEREST-664 Do not allow user to restore database if another restore …
percona/percona-everest-backend pull request #365
Opened 2023-12-19 13:41 UTC by gen1us2k

…is already in progress

**CHANGE DESCRIPTION**
---
**Problem:**
EVEREST-664

*Short explanation of the problem.*

**Related pull requests**

- [link]

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?

**Tests**
- [ ] Is an Integration test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?

2023-12-19 14:00 UTC, oksana-grishchenko requested changes
considering https://github.com/percona/everest-operator/pull/226 we can rely on the db cluster status `AppStateRestoring`, no need to hardcode the statuses

2023-12-19 16:13 UTC, oksana-grishchenko commented on api/database_cluster_restore.go
> +		})
logging the error before return here could be helpful for troubleshooting

2023-12-19 16:13 UTC, oksana-grishchenko approved these changes

2023-12-20 12:29 UTC, recharte approved these changes

2023-12-20 12:29 UTC, merged