EVEREST-173: resource usage endpoint
percona/percona-everest-backend pull request #72
Opened 2023-08-04 08:08 UTC by michal-kralik

- Returns available and allocated resources per cluster
- Resource allocation functionality has been ported from PMM

2023-08-07 07:43 UTC, gen1us2k requested changes
Thanks for the implementation. However, it misses API tests

2023-08-07 08:49 UTC, gen1us2k approved these changes

2023-08-07 10:07 UTC, michal-kralik commented
The test shall pass after https://github.com/percona/percona-everest-cli/pull/72 is merged

2023-08-08 10:34 UTC, recharte approved these changes
I'm not really sure that this custom logic for each k8s cluster type is entirely correct but it was working for PMM and I think it serves our current needs.

2023-08-08 10:34 UTC, recharte commented on pkg/kubernetes/kubernetes.go
> +			strings.Contains(storageClass.Provisioner, "standard") {
I don't think this is necessarily correct but we can fix this when we support other k8s cluster types.

2023-08-08 11:39 UTC, michal-kralik commented on pkg/kubernetes/kubernetes.go
> +			strings.Contains(storageClass.Provisioner, "standard") {
Me neither. I agree this may need a review.

2023-08-08 11:54 UTC, merged