EVEREST-239 Added cluster-info endpoint
percona/percona-everest-backend pull request #86
Opened 2023-08-08 19:58 UTC by gen1us2k

2023-08-10 09:49 UTC, oksana-grishchenko approved these changes
LGTM, however with the Everest provisioned from the latest `cli` `main` the API returns
```
{
    "message": "storageclasses.storage.k8s.io is forbidden: User \"system:serviceaccount:percona-everest:everest-admin\" cannot list resource \"storageclasses\" in API group \"storage.k8s.io\" at the cluster scope"
}
```
although the rights seems to be given🤔 Just wanted to let you know.

2023-08-10 11:29 UTC, gen1us2k commented
@oksana-grishchenko https://github.com/percona/percona-everest-cli/blob/main/pkg/install/operators.go#L877 please update your CLI =)

2023-08-10 16:17 UTC, michal-kralik requested changes

2023-08-10 16:17 UTC, michal-kralik commented on api/cluster-info.go
> +		return ctx.JSON(code, Error{Message: pointer.ToString(err.Error())})
Let's please return a meaningful message to the use and log the error.

2023-08-10 16:17 UTC, michal-kralik commented on api/cluster-info.go
> +		return ctx.JSON(code, Error{Message: pointer.ToString(err.Error())})
Let's please return a meaningful message to the use and log the error.

2023-08-10 16:27 UTC, gen1us2k commented on api/cluster-info.go
> +		return ctx.JSON(code, Error{Message: pointer.ToString(err.Error())})
Yeah. Makes sense. Thanks

2023-08-10 16:27 UTC, gen1us2k commented on api/cluster-info.go
> +		return ctx.JSON(code, Error{Message: pointer.ToString(err.Error())})
Yeah. Makes sense. Thanks

2023-08-14 06:32 UTC, michal-kralik requested changes

2023-08-14 06:32 UTC, michal-kralik commented on api/cluster-info.go
> +		return ctx.JSON(code, Error{Message: pointer.ToString("failed building connection to the Kubernetes cluster")})
Let's keep consistent styles by capitalizing the first letter.

2023-08-14 06:32 UTC, michal-kralik commented on api/cluster-info.go
> +		return ctx.JSON(code, Error{Message: pointer.ToString("failed getting Kubernetes cluster provider")})
The http status code is not correct here. Let's use `500`

2023-08-14 06:32 UTC, michal-kralik commented on api/cluster-info.go
> +		return ctx.JSON(code, Error{Message: pointer.ToString("failed getting storage classes")})
The http status code is not correct here. Let's use `500`

2023-08-14 08:12 UTC, michal-kralik approved these changes

2023-08-14 09:21 UTC, merged