EVEREST-107 Fixed security issues for api-tests
percona/percona-everest-backend pull request #87
Opened 2023-08-08 20:39 UTC by gen1us2k

2023-08-08 21:38 UTC, recharte approved these changes

2023-08-09 05:37 UTC, michal-kralik requested changes

2023-08-09 05:37 UTC, michal-kralik commented on api-tests/package.json
> +    "word-wrap": "^1.2.5"
Why do we need the new dependencies?
Anything broken with the api tests? They don't seem to be used.

2023-08-09 07:53 UTC, michal-kralik commented on api-tests/package.json
> +    "word-wrap": "^1.2.5"
Since they're indirect, the only way to update them is to update the affected package.
I believe updating them this way makes no difference, since the affected module will use its own vulnerable version.

2023-08-09 09:06 UTC, oksana-grishchenko approved these changes
LGTM, the CI is not happy about this update though.

2023-08-09 11:10 UTC, merged